#! /bin/sh
# First clone the chasebench repository, if not already present.

>setup.log

if [ -d chasebench ]
then	:
else
    echo "Downloading chasebench ..."
    git clone https://github.com/dbunibas/chasebench.git >> setup.log 2>&1
fi

# Then, check that the datasets are unzipped, or unzip them.

SCENARIOS=chasebench/scenarios
for dir in $SCENARIOS/LUBM/data/01k $SCENARIOS/LUBM/data/100 $SCENARIOS/Ontology-256/data $SCENARIOS/STB-128/data 
do
    (	cd $dir
	if [ -f data.zip.001 ]
	then
	    cat data.zip.* > x.zip
	    rm -f data.zip.*
	    echo "Unzipping data in $dir"
	    unzip -qq x.zip
	    rm -f x.zip
	fi
    )
done

for dir in datasets/*/*/common/data
do
    ( cd $dir
      echo "Unzipping data in $dir"
      gunzip -q -f -k *.gz 2>/dev/null
    )
done

# Then, clone vlog, if not present.

if [ -d vlog ]
then	:
else
    echo "Downloading vlog ..."
    git clone https://github.com/karmaresearch/vlog.git >> setup.log 2>&1
fi

# Then, build vlog if not already done.

if [ -f vlog/build/vlog ]
then	:
else
    echo "building vlog ..."
    cd vlog
    mkdir -p build
    cd build
    cmake .. >> ../../setup.log 2>&1
    make >> ../../setup.log 2>&1
    cd ../..
fi
